/** Declaration file generated by dts-gen */

declare module 'optimisedmt' {
    export = OptimisedMT;
}

export class OptimisedMT {
    constructor(_depth: any, _zeroValue: any, _leavesPerNode: any, _hashFunc: any);

    copy(): any;

    genMerklePath(_index: any): any;

    genMerkleSubrootPath(_startIndex: any, _endIndex: any): any;

    getChildIndices(_index: any): any;

    getLeaf(_index: any): any;

    getNode(_index: any): any;

    getParentIndices(_index: any): any;

    insert(_value: any): void;

    setNode(_index: any, _value: any): void;

    update(_index: any, _value: any): void;

    static calcChildIndices(_index: any, _leavesPerNode: any, _depth: any): any;

    static calcParentIndices(_index: any, _leavesPerNode: any, _depth: any): any;

    static unserialize(s: any): any;

    static verifyMerklePath(_proof: any, _hashFunc: any): any;

}

export const SNARK_FIELD_SIZE: any;

export function genRandomSalt(): any;

export function hash16(elements: any): any;

export function hash2(elements: any): any;

export function hash3(elements: any): any;

export function hash4(elements: any): any;

export function hash5(elements: any): any;

export function hashArray(input: any): any;

export function poseidon(inputs: any): any;

export function stringifyBigInts(o: any): any;

export function unstringifyBigInts(o: any): any;

